[package]
name = "zvidlib"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
description = "Frame-accurate video and audio I/O for native and WebAssembly applications"
repository = "https://github.com/lsegal/zvidlib"
readme = "README.md"
keywords = ["video", "audio", "webassembly", "webgl", "mp4"]
categories = ["multimedia", "wasm"]
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = []
native = []
web = []

[dependencies]
