[package]
name = "zvidlib-av1-encoder"
description = "Pure-Rust AV1 software encoder for zvidlib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zvidlib-core = { workspace = true }
zvidlib-av1 = { workspace = true }

[dev-dependencies]
zvidlib-av1-decoder = { path = "../zvidlib-av1-decoder" }
zvidlib-container = { path = "../zvidlib-container" }
