[package]
name = "zvidlib-opus"
description = "Opus decoding and encoding for zvidlib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zvidlib-core = { workspace = true }
opus-pure = { workspace = true }
